---
# tasks file for roles/openstack-volume-storage

- name: openstack volume | create source snapshot
  os_volume_snapshot:
    state: present
    display_name: "{{ openstack_volume_name }}-source"
    volume: "{{ openstack_volume_source }}"
    force: true
  register: results
  when: openstack_volume_source is defined

- name: openstack volume | create volume
  os_volume:
    state: present
    size: "{{ openstack_volume_size }}"
    display_name: "{{ openstack_volume_name }}"
    snapshot_id: "{{ results.snapshot.id | default(omit) }}"
    volume_type: "{{ openstack_volume_type | default(omit) }}"
    wait: "{{ openstack_volume_wait }}"

- name: openstack volume | delete source snapshot
  os_volume_snapshot:
    state: absent
    display_name: "{{ openstack_volume_name }}-source"
    volume: "{{ openstack_volume_source }}"
  when: openstack_volume_wait and (openstack_volume_source is defined)

- name: openstack volume | attach volume to host
  os_server_volume:
    state: present
    server: "{{ openstack_volume_vmname }}"
    volume: "{{ openstack_volume_name }}"
    device: "{{ openstack_volume_device | default(omit) }}"
  when: openstack_volume_wait and (openstack_volume_vmname is defined)
